### ISSUE TITLE
Allow using classes for colors

### ISSUE THREAD

**Issue by agentphoenix** [euvl/vue-js-toggle-button#15]
Was looking today for something like this and it's awesome. Great job @euvl!

Is there a way to use CSS classes to style the colors instead of hard-coding the colors as properties? Would love to be able to use this in a themeable system and give people the ability to make the switch match their theme.

Thanks!

**Comment by euvl** [comment]
Hey @agentphoenix,

Thanks!
Currently you can set colors only thought js api.

If you want set colors using css (or scss) and don't mind using `!important` flag, it might look this way (p.s. have not tested):

```scss
.vue-js-switch.my-class-name {
  .v-switch-core {
    background: red !important;
  }
  
  &.toggled > .v-switch-core {
    background: blue !important;
  }
}
```

```vue
<toggle-button class="my-class-name"/>
```
