### ISSUE TITLE
Allow the definition of colors through styling instead of configuration

### ISSUE THREAD

**Issue by lehni** [euvl/vue-js-toggle-button#36]
It would be nice if I could create the component in a way that would make it not set color styles from code, e.g.:

```html
<toggle-button :color="null">
```
```css
.vue-js-switch .v-switch-core {
  background: $color-grey
}
.vue-js-switch.toggled .v-switch-core {
  background: $color-active
}
```
